const mongoose = require("mongoose");
const timestamps = require('mongoose-timestamp');


const CondominiumSchema = new mongoose.Schema({
    
    name: {

        type: String,
        required: [true, "Please add condominium's name"],
        unique: true,
        trim: true,
        maxlength: [250, "Name can not be more than 250 characters"]
        
    },

    condominium_users: [mongoose.ObjectId],

    representative_id: {
        type: mongoose.ObjectId, 
        autogenerated: false
    },
    
});

CondominiumSchema.plugin(timestamps, {
    createdAt: 'created_at',
    updatedAt: 'updated_at'
});

module.exports = mongoose.model("Condominium", CondominiumSchema);